ceph code from kernel 4.19.295
xcp-ng-rpms/kernel pull request #9
Opened 2023-09-27 19:19 UTC by benapetr

I keep encountering weird issues and bugs with CEPH RBD using current 4.19.19 that seems to contain original code from 4.19.19 from many years ago. This patch should contain a huge number of fixes made to ceph code over the years.

2023-10-02 13:46 UTC, stormi commented
Reference forum discussion: https://xcp-ng.org/forum/topic/7789/what-is-kernel-alt

2024-02-26 12:19 UTC, stormi commented
Hi. Sorry for the long delay. Only now did I reach the bottom of my todo list. We'll review this and consider it for XCP-ng 8.3.

2024-02-28 17:21 UTC, tescande commented
Hi @benapetr,

Thank you for this PR.

Could you rebase your patch on top of master (it has changed since you submitted the PR) and add your Signed-off-by tag to the commit please ?

Otherwise, looks good to me.

2024-02-28 17:23 UTC, tescande requested changes
Hi @benapetr,

Thank you for this PR.

Could you rebase your patch on top of master (it has changed since you submitted the PR) and add your Signed-off-by tag to the commit please ?

Otherwise, looks good to me.

2024-02-29 07:41 UTC, tescande commented on SPECS/kernel.spec
You need to bump the Release version: `Release: %{?xsrel}.2%{?dist}`

And also add a changelog entry.

2024-03-08 21:35 UTC, benapetr commented
Hello,

I rebased and signed off my changes, but I don't know which version should be "bumped" and what do you want to see in the changelog

2024-03-08 22:31 UTC, benapetr commented
I added what I think might be the correct "version bump" as well as the comment, but I don't know if I incremented correct version, nor if the comment is in correct format

2024-06-06 10:19 UTC, benapetr commented
it's rebased again according to your requests

2024-06-07 10:20 UTC, stormi commented on SPECS/kernel.spec
> +Patch1000: ceph.patch
```suggestion

# XCP-ng patches
Patch1000: ceph.patch

```

2024-06-07 10:21 UTC, stormi commented on SPECS/kernel.spec
> +- Integrated ceph code from kernel 4.19.295
```suggestion
* Thu Jun 06 2024 Petr Bena <benapetr@gmail.com> - 4.19.19-8.0.33.2
- Integrated ceph code from kernel 4.19.295

```

Changelog entries are separated by a newline.

2024-06-11 07:54 UTC, tescande approved these changes
Looks good to me. Thanks a lot

2024-06-11 11:16 UTC, stormi approved these changes

2024-06-11 11:16 UTC, merged

2024-06-11 11:18 UTC, stormi commented
Koji build towards v8.3-incoming: http://koji.xcp-ng.org/taskinfo?taskID=55826